version: '3'
services:
  app:
    build: .
    container_name: barista-migrator
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - sail
    environment:
      DEBUG: "prisma*" # debugging prisma
      NODE_ENV: ${NODE_ENV:-PRODUCTION}
      SITEPOINT_CATEGORY_ID: ${SITEPOINT_CATEGORY_ID:-1}
      PROJECT_PROJECT_GROUP_ID: ${PROJECT_PROJECT_GROUP_ID:-1}
      SITE_CATEGORY_ID: ${SITE_CATEGORY_ID:-1}
      DATABASE_BARISTA_URL: ${DATABASE_BARISTA_URL}
      DATABASE_CAFEINS_URL: ${DATABASE_CAFEINS_URL}
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 20M