version: '3'
services:
  app:
    build: 
      context: .
      network: host # fixing error temporary failure resolving 'deb.debian.org'
    container_name: barista
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      DEBUG: "prisma*" # debugging prisma
      NODE_ENV: ${NODE_ENV:-PRODUCTION}
      SITEPOINT_CATEGORY_ID: ${SITEPOINT_CATEGORY_ID:-1}
      PROJECT_PROJECT_GROUP_ID: ${PROJECT_PROJECT_GROUP_ID:-1}
      SITE_CATEGORY_ID: ${SITE_CATEGORY_ID:-1}
      DATABASE_BARISTA_URL: ${DATABASE_BARISTA_URL}
      DATABASE_CAFEINS_URL: ${DATABASE_CAFEINS_URL}
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 20M
    networks:
      - barista

networks:
  barista:
    driver: bridge